name: Build and Test
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      # report each failing OS/toolchain build - useful for separating between OS failures vs. toolchain (nightly) failures
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v2
      - name: Build with toolchain ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          command: build
          args: --release --all-features
          toolchain: ${{ matrix.toolchain }}
      - name: Test with toolchain ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          command: test
          toolchain: ${{ matrix.toolchain }}
          args: --workspace --lib
      - name: Test docs with toolchain ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          command: test
          toolchain: ${{ matrix.toolchain }}
          args: --doc --all
      - name: Check formatting
        uses: actions-rs/toolchain@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/toolchain@v1
        with:
          command: clippy
          args: --workspace
