name: Lint Documentation
on:
  push:
    paths: 'docs/**'
    branches:
      - main
  pull_request:
    paths: 'docs/**'
jobs:
  lint_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: markdownlint
        run: markdownlint '**/*.md' -c .markdownlint.json
